services:
  postgres:
    image: postgres:17.9
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: elysia_start_template
    ports:
      - "5432:5432"
