name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: test

      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test

      RESEND_API_KEY: test

      EMAIL_FROM: test@test.com

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run drizzle:push

      - run: bun run lint

      - run: bun run fmt:check

      - run: bunx tsc --noEmit

      - run: bun run test
